import React, { useState } from "react";
import { ReactNode } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from "next/link";

import {
  Flex,
  Container,
  Heading,
  Stack,
  Text,
  Button,
  Icon,Box,useColorModeValue,SimpleGrid,
  IconProps,
} from '@chakra-ui/react';
import useAuth from "../hooks/useAuth";

import Footer from '../components/Front/Footer';
export default function Home() {
  const { logout, auth, setReloadUser } = useAuth();
  const [user, setUser] = useState(undefined);
  return (
    <>
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <Container maxW={'5xl'}>
      <Stack
        textAlign={'center'}
        align={'center'}
        spacing={{ base: 8, md: 10 }}
        py={{ base: 20, md: 28 }}>
        <Heading
          fontWeight={600}
          fontSize={{ base: '3xl', sm: '4xl', md: '6xl' }}
          lineHeight={'110%'}>
          {process.env.NAME_APP}{' '}
          <Text as={'span'} color={'orange'}>
            NextJS
          </Text>
        </Heading>
        <Text color={'gray.500'} maxW={'3xl'}>
          Marlon Falcon Hernandez
        </Text>
        <Stack spacing={6} direction={'row'}>
        
        {!auth && (
          <>
        <Link href="/login" passHref>
          <Button
            rounded={'full'}
            px={6}
            colorScheme={'orange'}>
            Login
          </Button>
        </Link>
        

          <Link href="/register" passHref>
            <Button rounded={'full'} px={6}>
              Register
            </Button>
          </Link>
          </>
          )}

        {auth && (
          <>
          <Link href="/dashboard" passHref>
          <Button
            rounded={'full'}
            px={6}
            colorScheme={'orange'}>
            Dashboard
          </Button>
        </Link>


          <Button rounded={"full"} ml={3} px={6} mb={6} onClick={logout} >
            {" "}
            Logout{" "}
          </Button>
          </>
        )}

         

        </Stack>
        
      </Stack>
    </Container>
      </main>
      </div>
      
      

      <Footer/>
    
      </>)
}
